import http from 'node:http';

const PORT=Number(process.env.PORT||3001);
const ALLOWED=['EGP','KWD','SAR','LBP','JOD','BHD','OMR','SDG','ILS'];
const origins=(process.env.CORS_ORIGINS||'*').split(',').map(v=>v.trim()).filter(Boolean);
let fiatCache={at:0,refreshAfter:0,rates:null,providerUpdatedAt:null,nextUpdateAt:null};
let usdtCache={at:0,priceUsd:null,updatedAt:null};
const originFor=o=>origins.includes('*')?'*':origins.includes(o)?o:origins[0]||'null';
const headers=req=>({'access-control-allow-origin':originFor(req.headers.origin),'access-control-allow-methods':'GET, OPTIONS','access-control-allow-headers':'Content-Type','vary':'Origin','x-content-type-options':'nosniff'});
function send(req,res,status,payload,cache='no-store'){const body=JSON.stringify(payload);res.writeHead(status,{...headers(req),'cache-control':cache,'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body)});res.end(body)}
function iso(sec){return Number.isFinite(sec)&&sec>0?new Date(sec*1000).toISOString():null}
async function fiat(){const now=Date.now();if(fiatCache.rates&&now<fiatCache.refreshAfter)return{...fiatCache,stale:false};try{const r=await fetch('https://open.er-api.com/v6/latest/EGP',{signal:AbortSignal.timeout(8000),headers:{'user-agent':'aou-tma-hub/5.0'}});if(!r.ok)throw new Error(`fx_${r.status}`);const p=await r.json();if(!p?.rates||p.result==='error')throw new Error('invalid_fx');const next=Number(p.time_next_update_unix)*1000;fiatCache={at:now,refreshAfter:Number.isFinite(next)&&next>now?next+60000:now+3600000,rates:p.rates,providerUpdatedAt:iso(Number(p.time_last_update_unix)),nextUpdateAt:iso(Number(p.time_next_update_unix))};return{...fiatCache,stale:false}}catch(e){if(fiatCache.rates&&now-fiatCache.at<172800000)return{...fiatCache,stale:true};throw e}}
async function usdt(){const now=Date.now();if(usdtCache.priceUsd&&now-usdtCache.at<60000)return usdtCache;try{const r=await fetch('https://api.coingecko.com/api/v3/simple/price?ids=tether&vs_currencies=usd&include_last_updated_at=true',{signal:AbortSignal.timeout(8000),headers:{accept:'application/json','user-agent':'aou-tma-hub/5.0'}});if(!r.ok)throw new Error(`usdt_${r.status}`);const p=await r.json();const priceUsd=Number(p?.tether?.usd);if(!Number.isFinite(priceUsd)||priceUsd<=0)throw new Error('invalid_usdt');usdtCache={at:now,priceUsd,updatedAt:iso(Number(p?.tether?.last_updated_at))};return usdtCache}catch(e){if(usdtCache.priceUsd&&now-usdtCache.at<1800000)return usdtCache;return{at:0,priceUsd:null,updatedAt:null}}}
async function quote(currency){const data=await fiat();const rate=currency==='EGP'?1:Number(data.rates?.[currency]);if(!Number.isFinite(rate)||rate<=0)throw new Error('rate_unavailable');let coin=null,usdtRate=null;if(currency!=='EGP'){coin=await usdt();const usdPerEgp=Number(data.rates?.USD);if(coin.priceUsd&&Number.isFinite(usdPerEgp)&&usdPerEgp>0)usdtRate=usdPerEgp/coin.priceUsd}return{base:'EGP',currency,rate,usdtRate,usdtUsdPrice:coin?.priceUsd||null,usdtSource:coin?.priceUsd?'coingecko.com':null,source:currency==='EGP'?'base':'open.er-api.com',cachedAt:new Date(data.at||Date.now()).toISOString(),providerUpdatedAt:data.providerUpdatedAt,nextUpdateAt:data.nextUpdateAt,cryptoUpdatedAt:coin?.updatedAt||null,status:currency==='EGP'?'base':data.stale?'stale':'fresh'}}

const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,headers(req));return res.end()}if(req.method!=='GET')return send(req,res,405,{error:'method_not_allowed'});const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(url.pathname==='/health')return send(req,res,200,{ok:true,service:'fx-service',version:'5.0.0'});if(url.pathname==='/api/currencies')return send(req,res,200,{base:'EGP',currencies:ALLOWED});if(url.pathname==='/api/fx'){const currency=(url.searchParams.get('currency')||'EGP').toUpperCase();if(!ALLOWED.includes(currency))return send(req,res,400,{error:'unsupported_currency'});try{return send(req,res,200,await quote(currency),'public, max-age=60, stale-while-revalidate=300')}catch(e){return send(req,res,503,{error:'fx_unavailable',message:e.message})}}return send(req,res,404,{error:'not_found'})});
server.listen(PORT,'0.0.0.0',()=>console.log(`FX service listening on ${PORT}`));
