import type { Language } from '../types';

export const copy = {
  en: {
    brandCaption:'Course services, clearly priced.', catalog:'Catalog', how:'How it works', support:'Support',
    liveFx:'LATEST FX · 9 OFFICIAL AOU BRANCHES', title1:'Find your course.', title2:'See the real price.',
    heroCopy:'Choose your AOU branch, search the course catalog, and see the local equivalent plus the USDT amount used for international branches.',
    searchPlaceholder:'Search TM105, BUS101, M110…', countryCurrency:'COUNTRY & CURRENCY', branch:'Branch', chooseBranch:'Choose AOU branch', selectedBranch:'Selected AOU branch',
    liveRate:'Latest rate', baseRate:'Base currency', staleRate:'Cached rate', rateUnavailable:'Rate temporarily unavailable', localCurrency:'Local currency', internationalPaymentCurrency:'International payment', paymentRule:'Payment rule', egyptLocalPayments:'Local EGP payment',
    courses:'Courses', searchableCatalog:'Searchable catalog', faculties:'Faculties', oneCatalog:'One clean catalog', currencies:'Currencies', aouCountries:'AOU branches', orderMetric:'Order', orderMetricValue:'< 1m', orderMetricCaption:'From search to request',
    catalogEyebrow:'COURSE CATALOG', chooseCourse:'Choose your course', catalogSubtitle:'Filter by faculty or search by course code, official course title, or description.', results:'results', all:'All', facultyComputer:'Computer Studies', facultyBusiness:'Business Studies', facultyEducation:'Education', facultyLanguage:'Language Studies',
    semester:'SEMESTER', service:'SERVICE', tmaSupport:'TMA support', startsFrom:'STARTS FROM', orderNow:'Order now', details:'Details', loadMore:'Load more courses', noResults:'No courses match your search.', noResultsHelp:'Try another course code or faculty.',
    requestTitle:'Send your request', requestSubtitle:'Review the course, branch, price and payment method before sending.', name:'Your name', contact:'Phone / WhatsApp', notes:'Notes (optional)', submit:'Submit request', submitting:'Sending…', cancel:'Cancel', required:'Please complete the required fields.', orderSuccess:'Request received', orderSuccessCopy:'Your request was saved successfully.', orderId:'Order ID', close:'Close', requestFailed:'Could not send the request. Please try again.',
    howTitle:'Built for a fast, clear order', step1Title:'Find your course', step1Copy:'Search by code, title or faculty.', step2Title:'Choose your AOU branch', step2Copy:'The site converts the EGP base price into the selected branch currency automatically.', step3Title:'Send your request', step3Copy:'Egypt pays locally. Other AOU branches pay the calculated USDT amount.', footer:'AOU TMA Hub · Product concept', tech:'React · FastAPI · Node.js',
    sort:'Sort', sortCode:'Course code', sortTitle:'Course title', titleUnavailable:'Title not found in current AOU catalogue', sortLow:'Price: low to high', sortHigh:'Price: high to low',
    descriptionPending:'Official AOU course description is being synchronized from the faculty catalogue.', descriptionSyncingShort:'Official description synchronization is pending for this exact course code.', descriptionUnavailable:'The current AOU catalogue does not publish a description under this exact course code.', courseDescription:'COURSE DESCRIPTION', aouSource:'Official AOU catalogue',
    paymentEyebrow:'PAYMENT OPTIONS', paymentTitle:'Payment methods for your selected branch', paymentSubtitle:'Egypt uses local wallets and InstaPay. Every non-Egypt AOU branch uses USDT.', paymentSecure:'Configured by environment', mobileWalletTransfer:'EGP mobile-wallet transfer', instantBankTransfer:'Instant bank transfer', internationalPayment:'International USDT payment', paymentConfiguredLater:'Destination is configured privately on deployment', paymentNetworkWarning:'For USDT, send only on the exact selected network. A transfer on the wrong network may be unrecoverable.', copy:'Copy', choosePayment:'Choose payment method', paymentDestination:'Payment destination', paymentReference:'Transfer reference / transaction hash (optional)', paymentReferencePlaceholder:'Example: InstaPay reference or USDT TxID',
    localPaymentForEgypt:'Egypt branch: local payment', localPaymentCopy:'Use a configured mobile wallet or InstaPay and keep the transfer reference.', usdtOnlyForBranch:'International branch: USDT only', usdtOnlyCopy:'The payable USDT amount is calculated from live fiat FX plus the current USDT/USD market price.', usdtRateUnavailable:'USDT quote is temporarily unavailable',
    onsiteExam:'ON-SITE', freeStudyPack:'Free study pack', claimPrice:'PRICE', free:'FREE', claimFree:'Claim free', studyResources:'study resources', studyResourcesIncluded:'Video + study files included', studyPackIncluded:'Included with this on-site course', watchExplanation:'Watch explanation video', videoWillBeAdded:'The explanation video will appear here once it is attached to this course.', filesWillBeAdded:'Study files will appear here once they are attached to this course.', claimTitle:'Claim the free study pack', claimSubtitle:'This on-site course is not sold as a normal order. Claim the free explanation video and study resources instead.', claimSuccess:'Free claim received', claimSuccessCopy:'Your free study-pack claim was recorded successfully.',
    themeSystem:'Follow device theme', themeDark:'Dark theme', themeLight:'Light theme', auto:'Auto', dark:'Dark', light:'Light',
  },
  ar: {
    brandCaption:'خدمات المواد بتسعير واضح وبسيط.', catalog:'المواد', how:'طريقة الطلب', support:'الدعم',
    liveFx:'آخر أسعار الصرف · 9 فروع رسمية للجامعة', title1:'دور على مادتك.', title2:'وشوف السعر الحقيقي.', heroCopy:'اختار فرع الجامعة، دور على المادة، وشوف السعر بعملة الفرع ومعاه قيمة USDT المطلوبة للفروع خارج مصر.', searchPlaceholder:'ابحث: TM105 أو BUS101 أو M110…', countryCurrency:'الدولة والعملة', branch:'الفرع', chooseBranch:'اختار فرع الجامعة', selectedBranch:'فرع الجامعة المختار',
    liveRate:'آخر سعر صرف', baseRate:'العملة الأساسية', staleRate:'آخر سعر محفوظ', rateUnavailable:'سعر التحويل غير متاح مؤقتًا', localCurrency:'عملة الفرع', internationalPaymentCurrency:'الدفع الدولي', paymentRule:'طريقة الدفع', egyptLocalPayments:'دفع محلي بالجنيه',
    courses:'مادة', searchableCatalog:'كتالوج قابل للبحث', faculties:'كليات', oneCatalog:'كل المواد في مكان واحد', currencies:'عملات', aouCountries:'فروع الجامعة', orderMetric:'الطلب', orderMetricValue:'< دقيقة', orderMetricCaption:'من البحث لإرسال الطلب',
    catalogEyebrow:'كتالوج المواد', chooseCourse:'اختار مادتك', catalogSubtitle:'فلتر حسب الكلية أو ابحث بكود المادة أو اسمها الرسمي أو وصفها.', results:'نتيجة', all:'الكل', facultyComputer:'الحاسبات', facultyBusiness:'إدارة الأعمال', facultyEducation:'التربية', facultyLanguage:'اللغات',
    semester:'الفصل', service:'الخدمة', tmaSupport:'خدمة TMA', startsFrom:'السعر يبدأ من', orderNow:'اطلب الآن', details:'التفاصيل', loadMore:'عرض مواد أكتر', noResults:'مفيش مواد مطابقة للبحث.', noResultsHelp:'جرّب كود مادة أو كلية مختلفة.',
    requestTitle:'ابعت طلبك', requestSubtitle:'راجع المادة والفرع والسعر وطريقة الدفع قبل الإرسال.', name:'اسمك', contact:'رقم الهاتف / واتساب', notes:'ملاحظات (اختياري)', submit:'إرسال الطلب', submitting:'جاري الإرسال…', cancel:'إلغاء', required:'كمّل البيانات المطلوبة الأول.', orderSuccess:'تم استلام الطلب', orderSuccessCopy:'طلبك اتحفظ بنجاح.', orderId:'رقم الطلب', close:'إغلاق', requestFailed:'حصلت مشكلة أثناء إرسال الطلب. جرّب تاني.',
    howTitle:'طلب سريع وواضح من أول خطوة', step1Title:'دور على المادة', step1Copy:'ابحث بالكود أو الاسم أو فلتر حسب الكلية.', step2Title:'اختار فرع الجامعة', step2Copy:'الموقع بيحوّل السعر الأساسي بالجنيه تلقائيًا لعملة الفرع المختار.', step3Title:'ابعت الطلب', step3Copy:'فرع مصر بيدفع محلي، وباقي الفروع بتدفع قيمة USDT المحسوبة.', footer:'AOU TMA Hub · نسخة المنتج', tech:'React · FastAPI · Node.js',
    sort:'الترتيب', sortCode:'كود المادة', sortTitle:'اسم المادة', titleUnavailable:'الاسم غير موجود في كتالوج AOU الحالي', sortLow:'السعر: الأقل أولًا', sortHigh:'السعر: الأعلى أولًا',
    descriptionPending:'وصف المادة الرسمي بيتزامن من كتالوج AOU الخاص بالكلية.', descriptionSyncingShort:'مزامنة الوصف الرسمي لسه معلقة للكود ده بالتحديد.', descriptionUnavailable:'كتالوج AOU الحالي مش ناشر وصف تحت كود المادة ده بنفس الصيغة.', courseDescription:'وصف المادة', aouSource:'كتالوج AOU الرسمي',
    paymentEyebrow:'طرق الدفع', paymentTitle:'طرق الدفع حسب الفرع المختار', paymentSubtitle:'فرع مصر بمحافظ إلكترونية وإنستا باي، وأي فرع خارج مصر الدفع فيه USDT.', paymentSecure:'بيانات التحويل من إعدادات السيرفر', mobileWalletTransfer:'تحويل محفظة إلكترونية بالجنيه', instantBankTransfer:'تحويل بنكي فوري', internationalPayment:'دفع USDT للطلبات الدولية', paymentConfiguredLater:'بيانات التحويل بتتحدد بشكل خاص وقت النشر', paymentNetworkWarning:'في USDT لازم تستخدم نفس الشبكة المختارة بالضبط؛ التحويل على شبكة غلط ممكن مايتسترجعش.', copy:'نسخ', choosePayment:'اختار طريقة الدفع', paymentDestination:'بيانات التحويل', paymentReference:'مرجع التحويل / Transaction Hash (اختياري)', paymentReferencePlaceholder:'مثال: مرجع InstaPay أو USDT TxID',
    localPaymentForEgypt:'فرع مصر: دفع محلي', localPaymentCopy:'استخدم محفظة إلكترونية أو InstaPay وخلي معاك مرجع التحويل.', usdtOnlyForBranch:'فرع خارج مصر: الدفع USDT فقط', usdtOnlyCopy:'قيمة USDT بتتحسب من سعر صرف العملات الحالي وسعر USDT مقابل الدولار.', usdtRateUnavailable:'سعر USDT غير متاح مؤقتًا',
    onsiteExam:'داخل الجامعة', freeStudyPack:'باقة مذاكرة مجانية', claimPrice:'السعر', free:'مجاني', claimFree:'Claim Free', studyResources:'مصادر مذاكرة', studyResourcesIncluded:'فيديو شرح + ملفات مذاكرة', studyPackIncluded:'مرفقة مع المادة الـOn-site', watchExplanation:'شاهد فيديو الشرح', videoWillBeAdded:'فيديو الشرح هيظهر هنا أول ما يتم ربطه بالمادة.', filesWillBeAdded:'ملفات المذاكرة هتظهر هنا أول ما يتم ربطها بالمادة.', claimTitle:'خد باقة المذاكرة مجانًا', claimSubtitle:'المادة الـOn-site مش بتظهر كطلب مدفوع عادي؛ بدل كده تاخد فيديو الشرح وملفات المذاكرة مجانًا.', claimSuccess:'تم تسجيل الـClaim المجاني', claimSuccessCopy:'تم تسجيل طلب باقة المذاكرة المجانية بنجاح.',
    themeSystem:'اتبع وضع الجهاز', themeDark:'الوضع الليلي', themeLight:'الوضع النهاري', auto:'تلقائي', dark:'ليلي', light:'نهاري',
  },
} satisfies Record<Language,Record<string,string>>;

export type Copy = typeof copy.en;
